on:
  pull_request:   # on every PR
  push:
    branches:
      - master    # on every push to master: the build artifacts are uploaded

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dylankenneally/github-actions-poke@v0.1
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  detail_master:
    runs-on: ubuntu-latest
    name: Detail the master branch
    # if the target branch is master
    if: ${{ github.base_ref == 'master' }}
    steps:
      - name: Dump dets
        run: echo "master branch"

  detail_branch:
    runs-on: ubuntu-latest
    name: Detail the source
    steps:
      - name: Dump dets
        run: echo "${{ github.head_ref }} branch"

  detail_more:
    runs-on: ubuntu-latest
    name: Details are here, happy reading
    steps:
      - name: Dump head reference branch
        run: echo "${{ github.head_ref }} branch"
      - name: Dump base reference branch
        run: echo "${{ github.base_ref }} branch"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
